#!/usr/bin/env python3
"""Take what the desk taught the comparator and make it permanent.

    python tools/apply_overrides.py                    # report only
    python tools/apply_overrides.py --write            # write the eval cases
    python tools/apply_overrides.py --file mine.json

A clerk disagreeing with a verdict is the most informative event this system
sees, and the easiest to lose. The workspace records the disagreement; this
turns it into two things that outlive the shipment:

1. **A blast-radius report.** Every verdict that changes across the whole
   inbox, named, before anything is written. Teaching the comparator that two
   companies are the same can silence a defect somewhere the clerk was not
   looking, so that is shown rather than discovered later.

2. **A case in the evaluation suite.** `eval/learned_cases.py` is generated
   from the overrides and runs on every test run. A clerk's judgement stops
   being a note on one email and becomes an assertion that has to keep
   passing.

The report also separates the overrides the base rules could handle on their
own from the ones that are irreducible facts about two companies. The first
kind is a missing rule in `normalize/` and should be fixed there; the second
kind belongs in the overrides file forever.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from sdoc.learned import Overrides           # noqa: E402
from sdoc.mailsource import BundleMailSource  # noqa: E402
from sdoc.normalize import values_agree       # noqa: E402
from sdoc.pipeline import run                 # noqa: E402

GENERATED = ROOT / "eval" / "learned_cases.py"

HEADER = '''#!/usr/bin/env python3
"""Generated by tools/apply_overrides.py - do not edit by hand.

Every case here came from a person at the desk disagreeing with a verdict.
Running this asserts the comparator still answers the way they said it should,
which is how a clerk's judgement outlives the shipment that produced it.

Regenerate after recording new corrections:

    python tools/apply_overrides.py --write
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from sdoc.learned import Overrides     # noqa: E402
from sdoc.normalize import values_agree  # noqa: E402

OVERRIDES_FILE = ROOT / "{overrides_name}"


def main() -> int:
    learned = Overrides.load(OVERRIDES_FILE)
    rows, failures, redundant = [], [], []

    for entry in learned.entries:
        by_rule = values_agree(entry.field, entry.si_value, entry.bl_value)
        applied = learned.verdict(entry.field, entry.si_value, entry.bl_value)
        if applied is not entry.agree:
            failures.append((entry, applied))
        if by_rule is entry.agree:
            redundant.append(entry)
        rows.append((entry, by_rule, applied))

    for entry, by_rule, applied in rows:
        mark = " " if applied is entry.agree else "X"
        note = "  (the rules already agree - the override is redundant)" \\
            if by_rule is entry.agree else ""
        print(f"{{mark}}{{entry.field:<15}} rules={{str(by_rule):<6}} "
              f"desk={{str(entry.agree):<6}} {{entry.who or 'someone'}}{{note}}")

    print()
    print(f"corrections recorded : {{len(rows)}}")
    print(f"honoured             : {{len(rows) - len(failures)}}")
    print(f"redundant            : {{len(redundant)}}  "
          f"(a rule in normalize/ could cover these)")
    if failures:
        print("\\nNOT HONOURED - the override file and the comparator disagree:")
        for entry, applied in failures:
            print(f"  {{entry.describe()}} -> got {{applied}}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def blast_radius(overrides: Overrides, source_dir: Path) -> list[dict]:
    """Every verdict that moves once the overrides are applied."""
    before = {r.email_id: r for r in run(BundleMailSource(source_dir))}
    after = {r.email_id: r for r in run(BundleMailSource(source_dir), learned=overrides)}

    moved = []
    for email_id, was in before.items():
        now = after[email_id]
        if (was.status, was.defect_fields) == (now.status, now.defect_fields):
            continue
        moved.append({
            "email_id": email_id,
            "reference": was.oc_number or was.booking_ref or "no reference",
            "from": f"{was.status} {sorted(was.defect_fields) or ''}".strip(),
            "to": f"{now.status} {sorted(now.defect_fields) or ''}".strip(),
            "silenced": bool(set(was.defect_fields) - set(now.defect_fields)),
        })
    return moved


def main() -> int:
    ap = argparse.ArgumentParser(description="apply desk corrections")
    ap.add_argument("--file", default=str(ROOT / "overrides.json"))
    ap.add_argument("--source", default=str(ROOT / "data"))
    ap.add_argument("--write", action="store_true",
                    help="write eval/learned_cases.py (default: report only)")
    args = ap.parse_args()

    path = Path(args.file)
    if not path.exists():
        print(f"no corrections file at {path}")
        print("record some in the workspace, then download them here.")
        return 0

    try:
        overrides = Overrides.load(path)
    except (ValueError, json.JSONDecodeError) as exc:
        print(f"{path} is not usable: {exc}")
        return 2

    print(f"{len(overrides)} correction(s) in {path.name}\n")
    for entry in overrides.entries:
        by_rule = values_agree(entry.field, entry.si_value, entry.bl_value)
        tag = "redundant" if by_rule is entry.agree else "needed"
        print(f"  [{tag:<9}] {entry.describe()}")
        print(f"              recorded by {entry.who or 'someone'}"
              f"{' on ' + entry.when if entry.when else ''}"
              f"{' - ' + entry.note if entry.note else ''}")
    print()

    moved = blast_radius(overrides, Path(args.source))
    if not moved:
        print("no verdict anywhere in the inbox changes.")
    else:
        silenced = [m for m in moved if m["silenced"]]
        print(f"{len(moved)} verdict(s) change, {len(silenced)} of them by "
              f"dropping a flag that was being raised:\n")
        for m in moved:
            mark = "!" if m["silenced"] else " "
            print(f" {mark} {m['email_id']}  {m['reference']:<14} "
                  f"{m['from']}  ->  {m['to']}")
        if silenced:
            print("\nThe lines marked ! stop a difference being reported. "
                  "Read them before writing.")

    if not args.write:
        print("\nreport only - pass --write to generate eval/learned_cases.py")
        return 0

    GENERATED.write_text(HEADER.format(overrides_name=path.name), encoding="utf-8")
    print(f"\nwrote {GENERATED.relative_to(ROOT)}")
    print("run it with: python eval/learned_cases.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
